version: '3'

services:
  dev-env:
    build: .
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    container_name: debug
    ports:
      - "7776:22"
      - "7777:7777"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
